import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const flourishEmbedScript = `
    !function() {
      const flourishDivs = document.querySelectorAll('.flourish-embed');
      if (flourishDivs.length > 0) {
        for (let i = 0; i < flourishDivs.length; i++) {
          const flourishDiv = flourishDivs[i];
          const flourishScript = document.createElement('script');
          flourishScript.src = 'https://public.flourish.studio/resources/embed.js';
          flourishScript.async = true;
          flourishDiv.appendChild(flourishScript);
        }
      }
    }();
  `;


  return (
    <>
      <Head>
        <title>SOP Impact Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script dangerouslySetInnerHTML={{ __html: flourishEmbedScript }} />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {/* <div id="flourish-embed" className={styles.flourishEmbed}>
        <iframe
          src='https://flo.uri.sh/visualisation/1957820/embed'
          title='Interactive or visual content'
          frameBorder='0'
          scrolling='no'
          className={styles.flourishPhotoStyler}>
          </iframe>
          </div>*/}
      </main>
    </>
  )
}