import Head from 'next/head'
import Image from 'next/image'
import FlourishEmbed1 from '../components/FlourishEmbed1';
import FlourishEmbed2 from '../components/FlourishEmbed2';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>SOP Impact Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h1>Welcome to My Page</h1>
          <FlourishEmbed1 />
        </div>
        <div>
          <h1>Separator</h1>
          <FlourishEmbed2 />
        </div>
      </main>
    </>
  )
}