import Head from 'next/head'
import Image from 'next/image'
import FlourishEmbed1 from '../components/FlourishEmbed1';
import FlourishEmbed2 from '../components/FlourishEmbed2';
import FlourishEmbed3 from '../components/FlourishEmbed3';
import Banner from '../components/Banner';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>SOP Impact Report</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <Banner />
          <div className={styles.separator}></div>
          <div className={styles.textContainer}>
            <h1>We create change-minded people, leaders, and communities.</h1>
            <p>We create future leaders who understand what it takes to move the world closer to peace.</p>
          </div>
          <FlourishEmbed1 />
          <div className={styles.separator}></div>
          <div className={styles.textContainer}>
            <h1>We create change-minded people, leaders, and communities.</h1>
            <p>We create future leaders who understand what it takes to move the world closer to peace.</p>
          </div>
          <Image 
            src="/Graphs.png" 
            alt="graphs" 
            width={1200} // The actual width of your image
            height={800} // The actual height of your image
            layout="responsive"
            className={styles.graphImage} 
          />
          <FlourishEmbed3 />
          <div className={styles.textContainer}>
            <h1>We create change-minded people, leaders, and communities.</h1>
            <p>We create future leaders who understand what it takes to move the world closer to peace.</p>
          </div>
          <FlourishEmbed2 />
        </div>
      </main>
    </>
  )
}